---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA,
                      options(digits = 3, scipen = 999))
library(tidyverse)
library(patchwork)
```

```{r}
df <- 
  here::here("data", "covid_data_final.csv") %>% 
  read_csv(show_col_types = FALSE) %>% 
  filter(date >= "2020-03-01") %>% 
  group_by(state) %>% 
  summarize(stringency = median(stringency_index_lag, na.rm = TRUE),
            state_level_index = state_level_index[date == "2021-04-04"],
            cases = median(cases_new, na.rm = TRUE))
```

```{r message=FALSE, eval = FALSE}
library(patchwork)
(df %>% 
  ggplot() + 
  aes(x = state_level_index, y = cases, label = state) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggrepel::geom_text_repel(size = 2, alpha = .5) | 
  # scale_x_reverse() +

df %>% 
  ggplot() + 
  aes(x = stringency, y = cases, label = state) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggrepel::geom_text_repel(size = 2, alpha = .5)) /
  # scale_x_reverse())   

df %>% 
  group_by(state) %>% 
  ggplot() + 
  aes(x = state_level_index, y = stringency, alpha = cases, size = cases, label = state) %>% 
  geom_point() +
  geom_vline(xintercept = 0, color = "red", size = 1.25, alpha = .5) +
  geom_hline(yintercept = 47.4, color = "blue", size = 1.25, alpha = .5) +
  ggrepel::geom_text_repel(aes(x = state_level_index, y = stringency, label = state), size = 2, alpha = .5)
  # scale_x_reverse()
  # geom_smooth(aes(x = state_level_index, y = cases/2.9), method = "lm", se = FALSE) +
  # scale_y_continuous(sec.axis = sec_axis(~ -2.9 * ., name = "cases"))
```

```{r eval=FALSE}
df %>% 
  group_by(state) %>% 
  # summarize(stringency = mean(stringency_index_lag, na.rm = TRUE)) %>% 
  summarize(med = median(stringency_index)) %>% 
  summarize(median(med, na.rm = TRUE))
```

```{r}
df %>% 
  mutate(cases = log(cases)) %>% 
  # filter(state_level_index < -.5 | state_level_index > .5) %>%
  ggplot() + 
  aes(x = state_level_index, y = cases, label = state) + 
  # geom_point() +
  # geom_vline(xintercept = 0, color = "red", size = 1.25, alpha = .5) +
  # geom_hline(yintercept = 47.4, color = "blue", size = 1.25, alpha = .5) + 
  # scale_x_reverse() + 
  # geom_smooth(method = "lm") +
  ggrepel::geom_text_repel(size = 3) + 
  theme_classic() + 
  labs(x = "Social Capital", y = "log(New Cases per Million)")
```

```{r plot-a}
plot_a <- 
df %>% 
  ggplot() + 
  aes(x = state_level_index, y = cases, label = state) + 
  geom_point(size = .5) + 
  geom_smooth(method = "lm") + 
  ggrepel::geom_text_repel(size = 2, alpha = .5) +
  theme_classic() + 
  labs(y = "Median Daily New Cases", x = "Social Capital")
```

```{r plot-b}
plot_b <- 
df %>% 
  ggplot() + 
  aes(x = stringency, y = cases, label = state) + 
  geom_point(size = .5) + 
  geom_smooth(method = "lm") + 
  ggrepel::geom_text_repel(size = 2, alpha = .5) +
  theme_classic() + 
  labs(x = "Median Stringency", y = NULL)
```

```{r plot-c}
plot_c <- 
df %>% 
  group_by(state) %>% 
  ggplot() + 
  aes(x = state_level_index, y = stringency, alpha = cases, size = cases, label = state) + 
  geom_vline(xintercept = 0, size = 1, alpha = .5) +
  geom_hline(yintercept = 47.4, size = 1, alpha = .5) +
  geom_point() +
  ggrepel::geom_text_repel(aes(x = state_level_index, y = stringency, label = state), size = 2, alpha = .5) + 
  labs(x = "Social Capital", y = "Median Stringency")  +
  theme_classic() +
  theme(legend.position = c(0.25,.10), 
        legend.direction = "horizontal", 
        legend.title = element_blank()) +
  ggtitle("Median Daily New Cases")
  
```

```{r}
plot_a | plot_b 
plot_c
```

