---
title: "Descriptive Stats"
author: "Tony Carilli"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    toc: false
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, message = FALSE,
                      options(digits = 3, scipen = 999))
library(tidyverse)
library(gt)
```

```{r message=FALSE, eval=FALSE}
df <-
  here::here("data", "covid_data_final.csv") %>%
  read_csv() %>%
  select(
    state,
    median_household_income,
    percent_adults_with_ba,
    percent_in_fair_or_poor_health,
    percent_black,
    density,
    percent_rural,
    percent_65,
    average_temperature,
    governor_political_affiliation
  ) %>% 
  group_by(state) %>% 
  distinct(
    state,
    median_household_income,
    percent_adults_with_ba,
    percent_in_fair_or_poor_health,
    percent_black,
    density,
    percent_rural,
    percent_65,
    average_temperature,
    governor_political_affiliation
  ) %>% 
  filter(state != "VI") %>% 
  ungroup()
```

```{r}
df <- # data
  here::here("data", "covid_data_final.csv") %>% 
  read_csv() %>% 
  filter(date >= "2020-03-01")
```


```{r eval=FALSE}
df %>% 
  pivot_longer(-c(state, governor_political_affiliation)) %>% 
  ggplot(aes(x = value)) + 
  geom_histogram(bins = 10) + 
  facet_wrap(~ name, scales = "free_x")
```

```{r eval=FALSE}
df %>% 
  select(-c(state, governor_political_affiliation)) %>% 
  pastecs::stat.desc() %>% 
  rownames_to_column("stat") %>% 
  filter(stat %in% c("nbr.val",
                          "min",
                          "max",
                          "mean", 
                          "median",
                          "std.dev")) %>% 
  gt() %>% 
  tab_header(title = "Descriptive Statistics",
             subtitle = "Controls") %>% 
  cols_label(stat = "Statistic", 
             median_household_income = "Median Household Income",
             percent_adults_with_ba = "Adults w/ BA (%)",
             percent_in_fair_or_poor_health = "Fair or Poor Health (%)",
             percent_black = "Black (%)",
             density = "Pop Density",
             percent_rural = "Rural Pop (%)",
             percent_65 = "Age > 65 (%)",
             average_temperature = "Average Temperature"
  ) %>% 
  cols_align("center") 
```


 
```{r}
df %>% 
  select(governor_political_affiliation) %>% 
  summarytools::freq()
```

```{r results='asis', eval=FALSE}
df %>% 
  select(cases_new, stringency_index, median_household_income, 
         percent_adults_with_ba, percent_in_fair_or_poor_health,
         percent_black, density, percent_rural, percent_65, average_temperature,
         state_level_index) %>% 
  as.data.frame() %>% 
  stargazer::stargazer(type = "html")
```

```{r eval=FALSE}
df %>% 
  select(cases_new, stringency_index, median_household_income, 
         percent_adults_with_ba, percent_in_fair_or_poor_health,
         percent_black, density, percent_rural, percent_65, average_temperature,
         state_level_index) %>% 
  pastecs::stat.desc() %>% 
  rownames_to_column("stat") %>% 
  filter(stat %in% c("nbr.val",
                          "min",
                          "max",
                          "mean", 
                          "median",
                          "std.dev")) %>% 
  pivot_longer(everything(),
    values_to = "Statistic",
    names_to = "Variable"
  )
  gt() %>% 
  tab_header(title = "Descriptive Statistics") %>% 
  cols_label(stat = "Statistic",
             cases_new = "New Cases",
             stringency_index = "Stringency Index",
             median_household_income = "Median Household Income",
             percent_adults_with_ba = "Adults w/ BA (%)",
             percent_in_fair_or_poor_health = "Fair or Poor Health (%)",
             percent_black = "Black (%)",
             density = "Pop Density",
             percent_rural = "Rural Pop (%)",
             percent_65 = "Age > 65 (%)",
             average_temperature = "Average Temperature",
             state_level_index = "Social Capital"
  ) %>% 
  cols_align("center") 
```

```{r}
df %>%
  select(
    cases_new,
    stringency_index,
    median_household_income,
    percent_adults_with_ba,
    percent_in_fair_or_poor_health,
    percent_black,
    density,
    percent_rural,
    percent_65,
    average_temperature,
    state_level_index
  ) %>%
  pastecs::stat.desc() %>%
  rownames_to_column("stat") %>%
  filter(stat %in% c("nbr.val",
                     "min",
                     "max",
                     "mean",
                     "median",
                     "std.dev")) %>%
  pivot_longer(-stat) %>%
  pivot_wider(names_from = "stat") %>%
  select(-name) %>% 
  mutate(row_names = c("New Cases", 
                       "Stringency Index",
                       "Median Household Income",
                       "% Adults w/ BA",
                       "% Fair or Poor Health",
                       "% Black",
                       "Pop. Density",
                       "% Rural",
                       "% > 65",
                       "Average Temperature",
                       "Social Capital Index")) %>% 
  gt(rowname_col = "row_names") %>%
  tab_header(title = "Descriptive Statistics") %>%
  cols_label(
    nbr.val = "N",
    min = "Min",
    max = "Max",
    median = "Median",
    mean = "Mean",
    std.dev = glue::glue("Standard \n Deviation")
  ) %>%
  cols_align("center") %>% 
  fmt_number(columns = c("mean","median"),
             decimals = 2)
```

```{r}
df %>%
    plm::plm(
      cases_new ~ stringency_index_lag * state_level_index +
        I(stringency_index_lag ^ 2),
      data = .,
      effect = "twoways",
      index = "state",
      method = "within"
    ) %>% 
  broom::tidy() %>% 
  pull(estimate) ->
  coefs
```


```{r}

sc_index <- c(-2, -1, 0, 1, 2)
stringency_index <-
  df %>%
  summarize(quant = quantile(stringency_index_lag, na.rm = TRUE)) %>%
  filter(between(quant, 1, 87)) %>% 
  pull(quant)
```


```{r}
new <- tibble()

for (i in seq_along(sc_index)) {
  for (j in seq_along(stringency_index)) {
    new[i, j] <- coefs[1] * stringency_index[j] +
      coefs[2] * stringency_index[j] ^ 2 +
      coefs[3] * stringency_index[j] * sc_index[i]
  }
}

new

new %>% 
  select(q1 = "...1",
         q2 = "...2",
         q3 = "...3") %>% 
  mutate(sc_index = sc_index) %>% 
  pivot_longer(-sc_index,
               names_to = "stringency_index",
               values_to = "new_cases") %>% 
  ggplot(aes(x = sc_index, y = new_cases, color = stringency_index)) + 
  geom_line()

# new %>% 
#   select("...50", "...89", "...1", "...39", "...60") %>% 
#   mutate(sc_index = sc_index) %>% 
#   ggplot(aes(y = ...50, x = sc_index)) +
#   geom_line() +
#   geom_line(aes(x = sc_index, y = ...89), color = "blue") +
#   geom_line(aes(x = sc_index, y = ...1), color = "red") +
#   geom_line(aes(x = sc_index, y = ...39), color = "green") +
#   geom_line(aes(x = sc_index, y = ...60), color = "purple")
```


```{r}
new %>%
  select(q1 = "...1",
         q2 = "...2",
         q3 = "...3") %>%
  mutate(sc_index = sc_index) %>%
  relocate(sc_index) %>%
  arrange(desc(sc_index)) %>%
  pivot_longer(-sc_index) %>%
  pivot_wider(values_from = value,
              names_from = sc_index) %>%
  # select(1 , 3:7) %>%
  arrange(desc(name)) %>% 
  mutate(name = c("High",
                  "Average",
                  "Low")) %>%
  gt(rowname_col = "name") %>%
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_body(columns = c(2, 6),
                                   rows = c(1, 3))) %>%
  cols_label(
    # name = "Prevention Level",
    `2` = "Strong",
    `1` = "Positive",
    `0` = "Average",
    `-1` = "Negative",
    `-2` = "Weak"
  ) %>%
  tab_spanner(label = "Level of Social Capital",
              columns = 2:6) %>%
  tab_stubhead(label = "Desire for Prevention")
  
```

```{r}
df %>% 
  select(stringency_index, stringency_index_lag) %>% 
  summary()

```


