---
title: "Final Tables"
author: "Tony Carilli"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = NA,
                      options(digits = 3, scipen = 999))
library(tidyverse)
library(plm)
library(stargazer)
library(gt)
df <- # data
  here::here("data", "covid_data_final.csv") %>% 
  read_csv() %>% 
  filter(date >= "2020-03-01")

sc_names <-
  df %>%
  names() 

soc_cap_measures <- sc_names[c(14:17, 46:53)]
```

# Table 1

```{r desc-stats, results='asis', eval=TRUE}
df %>%
  select(
    cases_new,
    stringency_index_lag,
    state_level_index,
    percent_adults_with_ba,
    percent_in_fair_or_poor_health,
    percent_black,
    percent_rural,
    percent_65,
    average_temperature,
    median_household_income,
    density
  ) %>%
  as.data.frame() %>%
  stargazer(
    type = "latex",
    summary.stat = c("n",
                     "min",
                     "max",
                     "mean",
                     "median",
                     "sd"),
    digits = 2,
    covariate.labels = c(
      "New Cases",
      "$\\mathrm{Stringency_{t-7}}$",
      "State Level Index",
      "\\% Bachelor's",
      "\\% Fair/Poor Health",
      "\\% Black",
      "\\% Rural",
      "\\% > 65",
      "Average Temperature",
      "Median Income",
      "Population Density"
    ),
    title = "Descriptive Statistics",
    header = FALSE
  )
```


# Table 2

```{r table-2, results='asis', eval=TRUE}
stargazer(
  df %>%
    plm(
      cases_new ~ stringency_index_lag * state_level_index +
        I(stringency_index_lag ^ 2),
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ),
  df %>%
    plm(
      cases_new ~ stringency_index_lag * state_level_index +
        I(stringency_index_lag ^ 2),
      data = .,
      effect = "twoways",
      index = "state",
      method = "within"
    ),
  df %>%
    plm(
      cases_new ~ stringency_index_lag * state_level_index +
        I(stringency_index_lag ^ 2) +
        median_household_income +
        percent_adults_with_ba +
        percent_in_fair_or_poor_health +
        percent_black +
        density +
        percent_rural +
        percent_65 +
        average_temperature +
        governor_political_affiliation,
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ),
  # df %>%
  #   plm(
  #     cases_new ~ stringency_index_lag * state_level_index  +
  #       I(stringency_index_lag ^ 2) +
  #       average_temperature +
  #       governor_political_affiliation +
  #       percent_in_fair_or_poor_health |
  #       median_household_income +
  #       percent_adults_with_ba +
  #       percent_black +
  #       density +
  #       percent_rural +
  #       percent_65 +
  #       average_temperature +
  #       governor_political_affiliation +
  #       percent_in_fair_or_poor_health +
  #       stringency_index_lag +
  #       I(stringency_index_lag) ^ 2,
  #     data = .,
  #     effect = "time",
  #     index = "state",
  #     model = "within"
  #   ),
  type = "latex",
  df = FALSE,
  covariate.labels = c(
    "$\\mathrm{Stringency_{t-7}}$",
    "Social K",
    "$\\mathrm{Stringency}_{t-7}^2$",
    "Median Income",
    "\\% Bachelor's",
    "\\% Fair/Poor Health",
    "\\% Black",
    "Population Density",
    "\\% Rural",
    "\\% > 65",
    "Average Temperature",
    "Republican Governor",
    "$\\mathrm{Stringency_{t-7}}$ * Social K"
  ),
  title = "Fixed Effects Regression Results",
  dep.var.labels = "Daily New Cases per Million",
  column.labels = c(
    "$\\mathrm{FE_{t}}$",
    "$\\mathrm{FE_{i,t}}$",
    "$\\mathrm{FE_t}$"
    # "$\\mathrm{IVFE_t}$"
  ),
  header = FALSE
)
```

# Table 3

```{r table-3, results='asis', eval=TRUE}
stargazer(
  # df %>%
  #   plm(
  #     cases_new ~ stringency_index_lag * state_level_index +
  #       I(stringency_index_lag ^ 2),
  #     data = .,
  #     effect = "twoways",
  #     index = "state",
  #     method = "within"
  #   ),
  df %>%
    plm(
      cases_new ~ stringency_index_lag * family_unity +
        stringency_index_lag * family_interaction +
        stringency_index_lag * social_support +
        stringency_index_lag * community_health +
        stringency_index_lag * institutional_health +
        stringency_index_lag * collective_efficacy +
        stringency_index_lag * philanthropic_health +
        I(stringency_index_lag ^ 2),
      data = .,
      effect = "twoways",
      index = "state",
      method = "within"
    ),
  type = "latex",
  df = FALSE,
  covariate.labels = c(
    "$\\mathrm{Stringency_{t-7}}$",
    "$\\mathrm{Stringency}_{t-7}^2$",
    "$\\mathrm{Stringency_{t-7}}$ * Family Unity",
    "$\\mathrm{Stringency_{t-7}}$ * Family Interaction",
    "$\\mathrm{Stringency_{t-7}}$ * Social Support",
    "$\\mathrm{Stringency_{t-7}}$ * Community Health",
    "$\\mathrm{Stringency_{t-7}}$ * Instutional Health",
    "$\\mathrm{Stringency_{t-7}}$ * Collective Efficacy",
    "$\\mathrm{Stringency_{t-7}}$ * Social Philanthropic Health"
  ),
  title = "Disaggregated Social Capital Regression Results",
  dep.var.labels = "Daily New Cases per Million",
  header = FALSE
)
```

# Table 4

```{r table-4, results='asis', eval=TRUE}
table_3_models <- list()

for (i in 1:4) {
  # for(i in 1:1)  {
  # sc_i <- soc_cap_measures[i]
  
  table_3_models[[i]] <-
    df %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2),
      data = .,
      effect = "twoways",
      index = "state",
      model = "within"
    ) 
}

names(table_3_models) <- soc_cap_measures[1:4]


stargazer(
  table_3_models,
  type = "latex",
  model.names = FALSE,
  df = FALSE,
  covariate.labels = c(
    "$\\mathrm{Stringency_{t-7}}$",
    "$\\mathrm{Stringency}_{t-7}^2$",
    "$\\mathrm{Stringency_{t-7}}$ * Social K"
  ),
  title = "Alternative Measures of Social Capital Regression Results",
  dep.var.labels = "Daily New Cases per Million",
  header = FALSE,
  column.labels = c(
    "Penn State",
    "Putnam",
    "Alesina La Ferrara",
    "Family Prosperity"
  )
)
```

# Table 5

```{r table-5, eval=TRUE, results='asis'}
df %>%
    plm::plm(
      cases_new ~ stringency_index_lag * state_level_index +
        I(stringency_index_lag ^ 2),
      data = .,
      effect = "twoways",
      index = "state",
      method = "within"
    ) %>%
# use equation 3 for table 5.
# df %>%
#     plm(
#       cases_new ~ stringency_index_lag * state_level_index +
#         I(stringency_index_lag ^ 2) +
#         median_household_income +
#         percent_adults_with_ba +
#         percent_in_fair_or_poor_health +
#         percent_black +
#         density +
#         percent_rural +
#         percent_65 +
#         average_temperature +
#         governor_political_affiliation,
#       data = .,
#       effect = "time",
#       index = "state",
#       model = "within"
#     ) %>%   
  broom::tidy() %>%
  pull(estimate) ->
  coefs


sc_index <- c(-2, -1, 0, 1, 2)
stringency_index <-
  df %>%
  summarize(quant = quantile(stringency_index_lag, na.rm = TRUE)) %>%
  # filter(between(quant, 1, 87)) %>% 
  filter(quant > 1 & quant < 87) %>% 
  pull(quant)

new <- tibble()

for (i in seq_along(sc_index)) {
  for (j in seq_along(stringency_index)) {
    new[i, j] <- coefs[1] * stringency_index[j] +
      coefs[2] * stringency_index[j] ^ 2 +
      coefs[3] * stringency_index[j] * sc_index[i]
  }
}

# for (i in seq_along(sc_index)) {
#   for (j in seq_along(stringency_index)) {
#     new[i, j] <- coefs[1] * stringency_index[j] +
#       coefs[2] * sc_index[j] +
#       coefs[3] * stringency_index[j] ^ 2 +
#       coefs[4] * median(df$median_household_income, na.rm = TRUE) +
#       coefs[5] * median(df$percent_adults_with_ba, na.rm = TRUE) +
#       coefs[6] * median(df$percent_in_fair_or_poor_health, na.rm = TRUE) +
#       coefs[7] *  median(df$percent_black, na.rm = TRUE) +
#       coefs[8] *  median(df$density, na.rm = TRUE) +
#       coefs[9] *  median(df$percent_rural, na.rm = TRUE) +
#       coefs[10] *  median(df$percent_65, na.rm = TRUE) +
#       coefs[11] *  median(df$average_temperature, na.rm = TRUE) +
#       coefs[12] *  0 +
#       coefs[13] * stringency_index[j] * sc_index[i]
#   }
# }


flextable::set_flextable_defaults(text.align = "left", fonts_ignore = TRUE)
new %>%
  select(q1 = "...1",
         q2 = "...2",
         q3 = "...3") %>%
  mutate(sc_index = sc_index) %>%
  relocate(sc_index) %>%
  arrange(desc(sc_index)) %>%
  pivot_longer(-sc_index) %>%
  pivot_wider(values_from = value,
              names_from = sc_index) %>%
  # select(1 , 3:7) %>%
  arrange(desc(name)) %>%
  mutate(name = c("High",
                  "Average",
                  "Low"))  %>%
  rename("Desire for Prevention" = name,
       "Strong" = `2`, 
       "Positive" = `1`,
       "Average" = `0`,
       "Negative" = `-1`,
       "Weak" = `-2`) %>% 
  mutate(across(Strong:Weak, ~ round(.x + 128.6353))) %>% 
  flextable::flextable() %>% 
  flextable::add_header_row(values = c("", "Level of Social Capital"),
                            colwidths = c(2, 4)) %>%
  flextable::align_text_col(align = "center", header = FALSE) %>% 
  flextable::set_caption("New Cases per Million Avoided") %>% 
  flextable::bold(i = c(1,3), j = c(2,6)) %>% 
  flextable::hline_top(part = "header") %>% 
  flextable::add_footer_lines(
    values = c("Strong and Weak Social Capital are 2 standard deviations above and below the mean level.",
               "High, Average, and Low are measured at the first, second, and third quartiles of the Stringency Index.")
  ) %>% 
  flextable::fontsize(size = 9, part = "footer") 
  

```


```{r}
new %>%
  select(q1 = "...1",
         q2 = "...2",
         q3 = "...3") %>%
  mutate(sc_index = sc_index) %>%
  relocate(sc_index) %>%
  arrange(desc(sc_index)) %>%
  pivot_longer(-sc_index) %>%
  pivot_wider(values_from = value,
              names_from = sc_index) %>%
  # select(1 , 3:7) %>%
  arrange(desc(name)) %>%
  mutate(name = c("High",
                  "Average",
                  "Low"))  %>%
  rename("Desire for Prevention" = name,
       "Strong" = `2`, 
       "Positive" = `1`,
       "Average" = `0`,
       "Negative" = `-1`,
       "Weak" = `-2`) %>% 
  mutate(across(Strong:Weak, ~ round(.x + 128.6353)))
```

