---
title: "More models"
author: "Tony Carilli"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA,
                      options(digits = 3, scipen = 999))
library(tidyverse)
library(plm)
library(stargazer)
df <- # data
  here::here("data", "covid_data_final.csv") %>% 
  read_csv()

sc_names <-
  df %>%
  names() 

soc_cap_measures <- sc_names[c(14:17, 46:64)]
```

# Table 1

```{r table-1, results='asis'}
stargazer(
   df %>%
    plm(
      cases_new ~ stringency_index_lag * state_level_index +
        I(stringency_index_lag ^ 2),
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ),
  
  df %>%
    plm(
      cases_new ~ stringency_index_lag * state_level_index +
        I(stringency_index_lag ^ 2) +
        median_household_income +
        percent_adults_with_ba +
        percent_in_fair_or_poor_health +
        percent_black +
        density +
        percent_rural +
        percent_65 +
        average_temperature +
        governor_political_affiliation,
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ),
  df %>%
    plm(
      cases_new ~ stringency_index_lag * state_level_index  +
        I(stringency_index_lag ^ 2) +
        average_temperature +
        governor_political_affiliation + 
        percent_in_fair_or_poor_health |
        median_household_income +
        percent_adults_with_ba +
        percent_black +
        density +
        percent_rural +
        percent_65 +
        average_temperature +
        governor_political_affiliation + 
        percent_in_fair_or_poor_health +
        stringency_index_lag +
        I(stringency_index_lag)^2,
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ),
  df %>% 
    plm(
      cases_new ~ stringency_index_lag * state_level_index + 
        I(stringency_index_lag^2),
      data = .,
      effect = "twoways",
      index = "state",
      method = "within"
    ),
    type = "html"
)

```

# Test for instruments

```{r iv-test, results='asis'}

stargazer(
  df %>%
    lm(
      state_level_index ~
        median_household_income +
        percent_adults_with_ba +
        # percent_in_fair_or_poor_health +
        percent_black +
        density +
        percent_rural +
        percent_65,
        # average_temperature +
        # governor_political_affiliation,
      data = .
    ),
  type = "html"
)
  

```

# Panel IV

```{r panel-iv, eval=FALSE}
 df %>%
    plm(
      cases_new ~ stringency_index_lag * state_level_index  +
        I(stringency_index_lag ^ 2) +
        average_temperature +
        governor_political_affiliation + 
        percent_in_fair_or_poor_health |
        median_household_income +
        percent_adults_with_ba +
        percent_black +
        density +
        percent_rural +
        percent_65 +
        average_temperature +
        governor_political_affiliation + 
        percent_in_fair_or_poor_health,
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ) %>% 
  summary()
```

# ANVOA

```{r anova, eval=FALSE}
one_way <- 
df %>%
  plm(
    cases_new ~ stringency_index_lag * state_level_index - state_level_index +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "time",
    index = "state",
    model = "within"
  ) 

two_way <- 
df %>% 
    plm(
      cases_new ~ stringency_index_lag * state_level_index + 
        I(stringency_index_lag^2),
      data = .,
      effect = "twoways",
      index = "state",
      method = "within"
    )

sum(one_way$residuals^2)
sum(two_way$residuals^2)

# Calculate F-stat for restrictions. 
((sum(one_way$residuals^2) - sum(two_way$residuals^2))/ 1) / (sum(two_way$residuals^2)/two_way$df.residual)



```


# Index and sub-index regressions complete two-way

```{r two-way-complete, eval=FALSE}

models_by_social_capital_measure <- list()

for (i in seq_along(soc_cap_measures)) {
  # for(i in 1:1)  {
  # sc_i <- soc_cap_measures[i]
  
  models_by_social_capital_measure[[i]] <-
    df %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2),
      data = .,
      effect = "twoways",
      index = "state",
      model = "within"
    ) 
}

names(models_by_social_capital_measure) <- soc_cap_measures


stargazer(models_by_social_capital_measure, type = "html")
```

```{r eval=FALSE}
pFtest(

df %>% 
    plm(
      cases_new ~ stringency_index_lag * state_level_index + 
        I(stringency_index_lag^2),
      data = .,
      effect = "twoways",
      index = "state",
      method = "within"
    ),
df %>%
  plm(
    cases_new ~ stringency_index_lag * state_level_index - state_level_index +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "time",
    index = "state",
    model = "within"
  )
)
```

```{r eval=FALSE}
pooltest(cases_new ~ stringency_index_lag * state_level_index + 
        I(stringency_index_lag^2),
      data = df,
      # effect = "twoways",
      # index = "state",
      method = "within")
```


```{r}
df %>% 
  select(median_household_income,
        percent_adults_with_ba,
        percent_black,
        density,
        percent_rural,
        percent_65,
        average_temperature,
        percent_in_fair_or_poor_health,
        state_level_index,
        cases_new) %>% 
  drop_na() %>% 
  cor()
  
```
# Index and sub-index regressions complete equation 2

```{r eq-2-models}
equation_2_models <- list()

for (i in seq_along(soc_cap_measures)) {
  equation_2_models[[i]] <-
    df %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2)
        median_household_income +
        percent_adults_with_ba +
        percent_in_fair_or_poor_health +
        percent_black +
        density +
        percent_rural +
        percent_65 +
        average_temperature +
        governor_political_affiliation, 
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ) %>% 
    summary()
}

names(equation_2_models) <- soc_cap_measures


equation_2_models
```



# Index and sub-index regressions complete equation 3

```{r eq-3-models}

equation_3_models <- list()

for (i in seq_along(soc_cap_measures)) {
  equation_3_models[[i]] <-
    df %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2) +
        average_temperature +
        governor_political_affiliation + 
        percent_in_fair_or_poor_health |
        median_household_income +
        percent_adults_with_ba +
        percent_black +
        density +
        percent_rural +
        percent_65 +
        average_temperature +
        governor_political_affiliation + 
        percent_in_fair_or_poor_health +
        stringency_index_lag +
        I(stringency_index_lag)^2,
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ) %>% 
    summary()
}

names(equation_3_models) <- soc_cap_measures


equation_3_models
```

# Index and sub-index regressions complete equation 4

```{r eq-4-models}
equation_4_models <- list()

for (i in seq_along(soc_cap_measures)) {
  equation_4_models[[i]] <-
    df %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2),
      data = .,
      effect = "twoways",
      index = "state",
      model = "within"
    ) %>% 
    summary()
}

names(equation_4_models) <- soc_cap_measures

equation_4_models
```

# Equation 2 by quarter

```{r eq-2-by-quarter}
equation_2_q1 <- list()

for (i in seq_along(soc_cap_measures)) {
  equation_2_q1[[i]] <-
    df %>%
    filter(date >= "2020-03-01", date < "2020-06-01") %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2) +
        median_household_income +
        percent_adults_with_ba +
        percent_in_fair_or_poor_health +
        percent_black +
        density +
        percent_rural +
        percent_65 +
        average_temperature +
        governor_political_affiliation,
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ) %>% 
    summary()
}

names(equation_2_q1) <- soc_cap_measures

equation_2_q2 <- list()

for (i in seq_along(soc_cap_measures)) {
  equation_2_q2[[i]] <-
    df %>%
    filter(date >= "2020-06-01", date < "2020-09-01") %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2) +
        median_household_income +
        percent_adults_with_ba +
        percent_in_fair_or_poor_health +
        percent_black +
        density +
        percent_rural +
        percent_65 +
        average_temperature +
        governor_political_affiliation,
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ) %>% 
    summary()
}

names(equation_2_q2) <- soc_cap_measures

equation_2_q3 <- list()

for (i in seq_along(soc_cap_measures)) {
  equation_2_q3[[i]] <-
    df %>%
    filter(date >= "2020-09-01", date < "2020-12-01") %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2) +
        median_household_income +
        percent_adults_with_ba +
        percent_in_fair_or_poor_health +
        percent_black +
        density +
        percent_rural +
        percent_65 +
        average_temperature +
        governor_political_affiliation,
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ) %>% 
    summary()
}

names(equation_2_q3) <- soc_cap_measures


equation_2_q4 <- list()

for (i in seq_along(soc_cap_measures)) {
  equation_2_q4[[i]] <-
    df %>%
    filter(date >= "2020-12-01", date < "2021-03-01") %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2) +
        median_household_income +
        percent_adults_with_ba +
        percent_in_fair_or_poor_health +
        percent_black +
        density +
        percent_rural +
        percent_65 +
        average_temperature +
        governor_political_affiliation,
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ) %>% 
    summary()
}

names(equation_2_q4) <- soc_cap_measures


equation_2_q5 <- list()

for (i in seq_along(soc_cap_measures)) {
  equation_2_q5[[i]] <-
    df %>%
    filter(date >= "2020-03-01") %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2) +
        median_household_income +
        percent_adults_with_ba +
        percent_in_fair_or_poor_health +
        percent_black +
        density +
        percent_rural +
        percent_65 +
        average_temperature +
        governor_political_affiliation,
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ) %>% 
    summary()
}

names(equation_2_q5) <- soc_cap_measures
```

```{r eq-2-q-results}
equation_2_q1
equation_2_q2
equation_2_q3
equation_2_q4
equation_2_q5
```

# Equation 3 by quarter

```{r eq-3-by-quarter}
equation_3_q1 <- list()

for (i in seq_along(soc_cap_measures)) {
  equation_3_q1[[i]] <-
    df %>%
    filter(date >= "2020-03-01", date < "2020-06-01") %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2) +
        average_temperature +
        governor_political_affiliation +
        percent_in_fair_or_poor_health |
        median_household_income +
        percent_adults_with_ba +
        percent_in_fair_or_poor_health +
        percent_black +
        density +
        percent_rural +
        percent_65 +
        average_temperature +
        governor_political_affiliation +
        stringency_index_lag +
        I(stringency_index_lag^2),
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ) %>% 
    summary()
}

names(equation_3_q1) <- soc_cap_measures

equation_3_q2 <- list()

for (i in seq_along(soc_cap_measures)) {
  equation_3_q2[[i]] <-
    df %>%
    filter(date >= "2020-06-01", date < "2020-09-01") %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2) +
         average_temperature +
        governor_political_affiliation +
        percent_in_fair_or_poor_health |
        median_household_income +
        percent_adults_with_ba +
        percent_in_fair_or_poor_health +
        percent_black +
        density +
        percent_rural +
        percent_65 +
        average_temperature +
        governor_political_affiliation +
        stringency_index_lag +
        I(stringency_index_lag^2),
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ) %>% 
    summary()
}

names(equation_3_q2) <- soc_cap_measures

equation_3_q3 <- list()

for (i in seq_along(soc_cap_measures)) {
  equation_3_q3[[i]] <-
    df %>%
    filter(date >= "2020-09-01", date < "2020-12-01") %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2) +
        average_temperature +
        governor_political_affiliation +
        percent_in_fair_or_poor_health |
        median_household_income +
        percent_adults_with_ba +
        percent_in_fair_or_poor_health +
        percent_black +
        density +
        percent_rural +
        percent_65 +
        average_temperature +
        governor_political_affiliation +
        stringency_index_lag +
        I(stringency_index_lag^2),
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ) %>% 
    summary()
}

names(equation_3_q3) <- soc_cap_measures


equation_3_q4 <- list()

for (i in seq_along(soc_cap_measures)) {
  equation_3_q4[[i]] <-
    df %>%
    filter(date >= "2020-12-01", date < "2021-03-01") %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2) +
         average_temperature +
        governor_political_affiliation +
        percent_in_fair_or_poor_health |
        median_household_income +
        percent_adults_with_ba +
        percent_in_fair_or_poor_health +
        percent_black +
        density +
        percent_rural +
        percent_65 +
        average_temperature +
        governor_political_affiliation +
        stringency_index_lag +
        I(stringency_index_lag^2),
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ) %>% 
    summary()
}

names(equation_3_q4) <- soc_cap_measures


equation_3_q5 <- list()

for (i in seq_along(soc_cap_measures)) {
  equation_3_q5[[i]] <-
    df %>%
    filter(date >= "2020-03-01") %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2) +
         average_temperature +
        governor_political_affiliation +
        percent_in_fair_or_poor_health |
        median_household_income +
        percent_adults_with_ba +
        percent_in_fair_or_poor_health +
        percent_black +
        density +
        percent_rural +
        percent_65 +
        average_temperature +
        governor_political_affiliation +
        stringency_index_lag +
        I(stringency_index_lag^2),
      data = .,
      effect = "time",
      index = "state",
      model = "within"
    ) %>% 
    summary()
}

names(equation_3_q5) <- soc_cap_measures
```
``
```{r eq-3-q-results}
equation_3_q1
equation_3_q2
equation_3_q3
equation_3_q4
equation_3_q5
```

# Equation 4 by quarter


```{r eq-4-by-quarters}
equation_4_q1 <- list()

for (i in seq_along(soc_cap_measures)) {
  # for(i in 1:1)  {
  # sc_i <- soc_cap_measures[i]
  
  equation_4_q1[[i]] <-
    df %>%
    filter(date >= "2020-03-01", date < "2020-06-01") %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2),
      data = .,
      effect = "twoways",
      index = "state",
      model = "within"
    ) %>%
    summary()
}

names(equation_4_q1) <- soc_cap_measures



equation_4_q2 <- list()

for (i in seq_along(soc_cap_measures)) {
  # for(i in 1:1)  {
  # sc_i <- soc_cap_measures[i]
  
  equation_4_q2[[i]] <-
    df %>%
    filter(date >= "2020-06-01", date < "2020-09-01") %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2),
      data = .,
      effect = "twoways",
      index = "state",
      model = "within"
    ) %>%
    summary()
}

names(equation_4_q2) <- soc_cap_measures

equation_4_q3 <- list()

for (i in seq_along(soc_cap_measures)) {
  # for(i in 1:1)  {
  # sc_i <- soc_cap_measures[i]
  
  equation_4_q3[[i]] <-
    df %>%
    filter(date >= "2020-09-01", date < "2020-12-01") %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2),
      data = .,
      effect = "twoways",
      index = "state",
      model = "within"
    ) %>%
    summary()
}

names(equation_4_q3) <- soc_cap_measures

equation_4_q4 <- list()

for (i in seq_along(soc_cap_measures)) {
  # for(i in 1:1)  {
  # sc_i <- soc_cap_measures[i]
  
  equation_4_q4[[i]] <-
    df %>%
    filter(date >= "2020-12-01", date < "2021-03-01") %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2),
      data = .,
      effect = "twoways",
      index = "state",
      model = "within"
    ) %>%
    summary()
}

names(equation_4_q4) <- soc_cap_measures

equation_4_q5 <- list()

for (i in seq_along(soc_cap_measures)) {
  # for(i in 1:1)  {
  # sc_i <- soc_cap_measures[i]
  
  equation_4_q5[[i]] <-
    df %>%
    filter(date >= "2021-03-01") %>%
    plm(
      cases_new ~ stringency_index_lag * get(soc_cap_measures[i]) +
        I(stringency_index_lag ^ 2),
      data = .,
      effect = "twoways",
      index = "state",
      model = "within"
    ) %>%
    summary()
}

names(equation_4_q5) <- soc_cap_measures
```

```{r eq-4-results}
equation_4_q1
equation_4_q2
equation_4_q3
equation_4_q4
equation_4_q5
```

