---
title: "updated models"
author: "Tony Carilli"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA,
                      options(digits = 3, scipen = 999))
library(tidyverse)
library(plm)
library(bibtex)
library(stargazer)
df <- # data
  here::here("data", "covid_data_final.csv") %>% 
  read_csv()
```

# Table 2 Regressions

```{r table-2}


df %>%
  plm(
    cases_new ~ stringency_index_lag * state_level_index +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  )


df %>%
  plm(
    cases_new ~ stringency_index_lag * state_level_index +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "time",
    index = "state",
    model = "within"
  )


df %>%
  plm(
    cases_new ~ stringency_index_lag * state_level_index +
      I(stringency_index_lag ^ 2) +
      median_household_income +
      percent_adults_with_ba +
      percent_in_fair_or_poor_health +
      percent_black +
      density +
      percent_rural +
      percent_65 +
      average_temperature +
      governor_political_affiliation,
    data = .,
    effect = "time",
    index = "state",
    model = "within"
  )


```

# Table 3 Regressions

```{r table-3, results='asis', message=FALSE}
model_penn_state <- 
  df %>%
  mutate(sc = scp_version_of_penn_state_index) %>% 
  plm(
    cases_new ~ stringency_index_lag * sc +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  )

model_putnam <- 
  df %>%
  mutate(sc = putnam_index) %>% 
  plm(
    cases_new ~ stringency_index_lag * sc +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  )

model_alesina <- 
  df %>%
  mutate(sc = alesina_la_ferrara_social_capital_group) %>% 
  plm(
    cases_new ~ stringency_index_lag * sc +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  )

stargazer(
  model_alesina,
  model_putnam,
  model_penn_state,
  type = "html",
  df = FALSE,
  header = FALSE,
  covariate.labels = c(
    "Stringency Index",
    "Stringency Index squared",
    "Stringency Index * Social Capital Index"
  ),
  title = "Alternate Social Capital Measures",
  column.labels = c(
    "Alesina La Ferrara",
    "Putnam Index",
    "Penn State Index"
  ),
  dep.var.labels = "Daily New Cases",
  notes = "Each model estimtate with two-way fixed effects."
)
```

# Table 4 Regressions

```{r table-4, results='asis', message=FALSE}
model_penn_state_one_way <-
  df %>%
  mutate(sc = scp_version_of_penn_state_index) %>%
  plm(
    cases_new ~ stringency_index_lag * sc +
      I(stringency_index_lag ^ 2) +
      median_household_income +
      percent_adults_with_ba +
      percent_in_fair_or_poor_health +
      percent_black +
      density +
      percent_rural +
      percent_65 +
      average_temperature +
      governor_political_affiliation,
    data = .,
    effect = "time",
    index = "state",
    model = "within"
  )

model_putnam_one_way <-
  df %>%
  mutate(sc = putnam_index) %>%
  plm(
    cases_new ~ stringency_index_lag * sc +
      I(stringency_index_lag ^ 2) +
      median_household_income +
      percent_adults_with_ba +
      percent_in_fair_or_poor_health +
      percent_black +
      density +
      percent_rural +
      percent_65 +
      average_temperature +
      governor_political_affiliation,
    data = .,
    effect = "time",
    index = "state",
    model = "within"
  )

model_alesina_one_way <-
  df %>%
  mutate(sc = alesina_la_ferrara_social_capital_group) %>%
  plm(
    cases_new ~ stringency_index_lag * sc +
      I(stringency_index_lag ^ 2) +
      median_household_income +
      percent_adults_with_ba +
      percent_in_fair_or_poor_health +
      percent_black +
      density +
      percent_rural +
      percent_65 +
      average_temperature +
      governor_political_affiliation,
    data = .,
    effect = "time",
    index = "state",
    model = "within"
  )

stargazer(
  model_alesina_one_way,
  model_putnam_one_way,
  model_penn_state_one_way,
  type = "html",
  header = FALSE,
  df = FALSE,
  # omit = c(
  #   "median_household_income",
  #   "percent_adults_with_ba",
  #   "percent_in_fair_or_poor_health",
  #   "percent_black",
  #   "density",
  #   "percent_rural",
  #   "percent_65",
  #   "average_temperature",
  #   "governor_political_affiliation"
  # ),
  covariate.labels = c(
    "Stringency Index",
    "Stringency Index squared",
    "Social Capital Index",
    "Stringency Index * Social Capital Index"
  ),
  title = "Alternate Social Capital Measures",
  column.labels = c(
    "Alesina La Ferrara",
    "Putnam Index",
    "Penn State Index"
  ),
  order = c(1, 3, 2, 4),
  dep.var.labels = "Daily New Cases per Million",
  notes = "One-way fixed effects with controls not reported."
)
```

# Table 5 Regressions

```{r table-5, results='asis', message=FALSE}
model_oneway_with_controls_pre_july_4 <- 
  df %>% 
  filter(date <= "2020-07-04") %>% 
  plm(
    cases_new ~ stringency_index_lag * state_level_index +
      I(stringency_index_lag ^ 2) +
      median_household_income +
      percent_adults_with_ba +
      percent_in_fair_or_poor_health +
      percent_black +
      density +
      percent_rural +
      percent_65 +
      average_temperature +
      governor_political_affiliation,
    data = .,
    effect = "time",
    index = "state",
    model = "within"
  )
  
  model_oneway_with_controls_post_july_4 <- 
  df %>% 
  filter(date > "2020-07-04") %>% 
  plm(
    cases_new ~ stringency_index_lag * state_level_index +
      I(stringency_index_lag ^ 2) +
      median_household_income +
      percent_adults_with_ba +
      percent_in_fair_or_poor_health +
      percent_black +
      density +
      percent_rural +
      percent_65 +
      average_temperature +
      governor_political_affiliation,
    data = .,
    effect = "time",
    index = "state",
    model = "within"
  )
  
stargazer(
  model_oneway_with_controls_pre_july_4,
  model_oneway_with_controls_post_july_4,
  type = "html",
  header = FALSE,
  df = FALSE,
  # omit = c(
  #   "median_household_income",
  #   "percent_adults_with_ba",
  #   "percent_in_fair_or_poor_health",
  #   "percent_black",
  #   "density",
  #   "percent_rural",
  #   "percent_65",
  #   "average_temperature",
  #   "governor_political_affiliation"
  # ),
  covariate.labels = c(
    "Stringency Index",
    "Stringency Index squared",
    "Social Capital Index",
    "Stringency Index * Social Capital Index"
  ),
  order = c(1, 3, 2, 4),
  title = "Regression Results pre and post July 4",
  column.labels = c("Mar - July 4",
                    "July 5 - "),
  dep.var.labels = "Daily New Cases per Million",
  notes = "One-way fixed effects with controls not reported."
) 
```

# Quarterly Regressions - State-level index - one way

```{r}
df %>% 
  filter(date < "2020-06-01") %>% 
  plm(
    cases_new ~ stringency_index_lag * state_level_index +
      I(stringency_index_lag ^ 2) +
      median_household_income +
      percent_adults_with_ba +
      percent_in_fair_or_poor_health +
      percent_black +
      density +
      percent_rural +
      percent_65 +
      average_temperature +
      governor_political_affiliation,
    data = .,
    effect = "time",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>% 
  filter(date >= "2020-06-01", date < "2020-09-01") %>% 
  plm(
    cases_new ~ stringency_index_lag * state_level_index +
      I(stringency_index_lag ^ 2) +
      median_household_income +
      percent_adults_with_ba +
      percent_in_fair_or_poor_health +
      percent_black +
      density +
      percent_rural +
      percent_65 +
      average_temperature +
      governor_political_affiliation,
    data = .,
    effect = "time",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>% 
  filter(date >= "2020-09-01", date < "2020-12-01") %>% 
  plm(
    cases_new ~ stringency_index_lag * state_level_index +
      I(stringency_index_lag ^ 2) +
      median_household_income +
      percent_adults_with_ba +
      percent_in_fair_or_poor_health +
      percent_black +
      density +
      percent_rural +
      percent_65 +
      average_temperature +
      governor_political_affiliation,
    data = .,
    effect = "time",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>% 
  filter(date >= "2020-12-01", date < "2021-03-01") %>% 
  plm(
    cases_new ~ stringency_index_lag * state_level_index +
      I(stringency_index_lag ^ 2) +
      median_household_income +
      percent_adults_with_ba +
      percent_in_fair_or_poor_health +
      percent_black +
      density +
      percent_rural +
      percent_65 +
      average_temperature +
      governor_political_affiliation,
    data = .,
    effect = "time",
    index = "state",
    model = "within"
  ) %>% 
  summary()
```

# Quarterly Regressions - State-level index - two ways

```{r}
df %>%
  filter(date < "2020-06-01") %>% 
  plm(
    cases_new ~ stringency_index_lag * state_level_index +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  filter(date >= "2020-06-01", date < "2020-09-01") %>% 
  plm(
    cases_new ~ stringency_index_lag * state_level_index +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  filter(date >= "2020-09-01", date < "2020-12-01") %>% 
  plm(
    cases_new ~ stringency_index_lag * state_level_index +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  filter(date >= "2020-12-01", date < "2021-03-01") %>% 
  plm(
    cases_new ~ stringency_index_lag * state_level_index +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()
```


# Sub-indices regressions

```{r}
df %>%
  plm(
    cases_new ~ stringency_index_lag * family_unity +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  plm(
    cases_new ~ stringency_index_lag * family_interaction +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  plm(
    cases_new ~ stringency_index_lag * social_support +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  plm(
    cases_new ~ stringency_index_lag * community_health +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  plm(
    cases_new ~ stringency_index_lag * institutional_health +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  plm(
    cases_new ~ stringency_index_lag * philanthropic_health +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  plm(
    cases_new ~ stringency_index_lag * average_number_of_close_friends +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  plm(
    cases_new ~ stringency_index_lag * percent_who_trust_all_most_neighbors +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  plm(
    cases_new ~ stringency_index_lag * membership_organizations_p_1_000 +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  plm(
    cases_new ~ stringency_index_lag * non_religious_non_profits_plus_religious_congregations_p_1_000 +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  plm(
    cases_new ~ stringency_index_lag * percent_participated_in_demonstration +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  plm(
    cases_new ~ stringency_index_lag * percent_who_volunteered_for_a_group +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  plm(
    cases_new ~ stringency_index_lag * percent_attended_public_meeting +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  plm(
    cases_new ~ stringency_index_lag * percent_worked_with_neighbors_to_improve_fix_something +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  plm(
    cases_new ~ stringency_index_lag * percent_served_on_committee_or_as_group_officer +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()

df %>%
  plm(
    cases_new ~ stringency_index_lag * percent_have_some_great_confidence_in_media +
      I(stringency_index_lag ^ 2),
    data = .,
    effect = "twoways",
    index = "state",
    model = "within"
  ) %>% 
  summary()
```

```{r}
sc_names <-
  df %>%
  names() 

soc_cap_measures <- sc_names[c(20:23, 52:70)]  
  
```


```{r}

models_by_social_capital_measure <- list()

for(i in seq_along(soc_cap_measures)) {
  
  # sc_i <- soc_cap_measures[i]
  
  models_by_social_capital_measure[[i]] <-
    plm(
      cases_new ~ stringency_index_lag * soc_cap_measures[i] +
        I(stringency_index_lag ^ 2),
      data = df,
      effect = "twoways",
      index = "state",
      model = "within"
    ) %>% 
    summary()
}

```





