---
output:
  word_document:
    fig_height: 4.25
    fig_width: 6.5
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, fig.lp = '',
                      options(digits = 3, scipen = 999))
library(tidyverse)
library(patchwork)
```

```{r include=FALSE}
df <- 
  here::here("data", "covid_data_final.csv") %>% 
  read_csv(show_col_types = FALSE) %>% 
  filter(date >= "2020-03-01") %>% 
  group_by(state) %>% 
  summarize(stringency = median(stringency_index_lag, na.rm = TRUE),
            state_level_index = state_level_index[date == "2021-04-04"],
            cases = median(cases_new, na.rm = TRUE))
```

```{r plot-a, include=FALSE, message=FALSE}
plot_a <- 
df %>% 
  ggplot() + 
  aes(x = state_level_index, y = cases, label = state) + 
  geom_point(size = .5) + 
  geom_smooth(method = "lm", se = FALSE, color = "dark grey") + 
  ggrepel::geom_text_repel(size = 2.5, alpha = .75,
                           mapping = aes(family = "serif"),
                           max.overlaps = 12) +
  theme_classic() + 
  labs(y = "Median Daily New Cases per Million", x = "Social Capital") +
  theme(text = element_text(family = "serif")) 
```

```{r plot-b, include=FALSE, message=FALSE}
plot_b <- 
df %>% 
  ggplot() + 
  aes(x = stringency, y = cases, label = state) + 
  geom_point(size = .5) + 
  geom_smooth(method = "lm", se = FALSE, color = "dark grey") + 
  ggrepel::geom_text_repel(size = 2.5, alpha = .75,
                           mapping = aes(family = "serif"),
                           max.overlaps = 12) +
  theme_classic() + 
  labs(x = "Median Lagged Stringency", y = NULL) +
  theme(text = element_text(family = "serif"))
```



```{r message=FALSE, echo=FALSE}
(plot_a | plot_b )
```



