---
output: 
  pdf_document:
    fig_caption: yes
---

```{r setup-fig1, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, fig.lp = '',
                      options(digits = 3, scipen = 999))
library(tidyverse)
library(patchwork)
```

```{r include=FALSE}
df <- 
  here::here("data", "covid_data_final.csv") %>% 
  read_csv(show_col_types = FALSE) %>% 
  filter(date >= "2020-03-01") %>% 
  group_by(state) %>% 
  summarize(stringency = median(stringency_index_lag, na.rm = TRUE),
            state_level_index = state_level_index[date == "2021-04-04"],
            cases = median(cases_new, na.rm = TRUE))
```


```{r plot-c, include=FALSE}
plot_c <-
df %>% 
  group_by(state) %>% 
  ggplot() + 
  aes(x = state_level_index, y = stringency, alpha = cases, size = cases, label = state) + 
  geom_vline(xintercept = 0, size = 1, alpha = .5) +
  geom_hline(yintercept = 47.9, size = 1, alpha = .5) +
  geom_point() +
  ggrepel::geom_text_repel(aes(x = state_level_index, y = stringency, label = state), size = 3, alpha = .5) + 
  labs(x = "Social Capital", y = "Stringency")  +
  theme_classic() +
  theme(legend.position = c(0.25,.10), 
        legend.direction = "horizontal", 
        legend.title = element_blank()) +
  annotate(geom = "text", x = -1.65, y = 55, label = "Median Level of Stringency") +
  annotate(geom = "segment", x = -1.5, y = 53.5, xend = -1.6, yend = 48,
           arrow = arrow(length = unit(2, "mm"))) + 
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank()) +
  annotate(geom = "text", x = 1, y = 20, label = "Social Capital = 0") +
  annotate(geom = "segment", x = .54, y = 19.65, xend = 0, yend = 25,
           arrow = arrow(length = unit(2, "mm")))
```


```{r message=FALSE, echo=FALSE, fig.cap="Median Daily New Cases per Million"}
plot_c
```

