---
output: pdf_document
---

```{r setup-table-5, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = NA,
                      options(digits = 3, scipen = 999))
library(tidyverse)
library(plm)
library(stargazer)
```

```{r data-5, include=FALSE}
df <- # data
  here::here("data", "covid_data_final.csv") %>% 
  read_csv(show_col_types = "FALSE") %>% 
  filter(date >= "2020-03-01")

sc_names <-
  df %>%
  names() 

soc_cap_measures <- sc_names[c(14:17, 46:53)]
```


```{r table-5, results='asis'}
stargazer(
  df %>%
    plm(
      cases_new ~ stringency_index_lag * family_unity +
        stringency_index_lag * family_interaction +
        stringency_index_lag * social_support +
        stringency_index_lag * community_health +
        stringency_index_lag * institutional_health +
        stringency_index_lag * collective_efficacy +
        stringency_index_lag * philanthropic_health +
        I(stringency_index_lag ^ 2),
      data = .,
      effect = "twoways",
      index = "state",
      method = "within"
    ) %>%
    lmtest::coeftest(vcovHC(
      .,
      method = "white1",
      type = "HC0",
      cluster = "group"
    )),
  type = "latex",
  df = FALSE,
  covariate.labels = c(
    "$\\mathrm{Stringency_{t-7}}$",
    "$\\mathrm{Stringency}_{t-7}^2$",
    "$\\mathrm{Stringency_{t-7}}$ * Family Unity",
    "$\\mathrm{Stringency_{t-7}}$ * Family Interaction",
    "$\\mathrm{Stringency_{t-7}}$ * Social Support",
    "$\\mathrm{Stringency_{t-7}}$ * Community Health",
    "$\\mathrm{Stringency_{t-7}}$ * Instutional Health",
    "$\\mathrm{Stringency_{t-7}}$ * Collective Efficacy",
    "$\\mathrm{Stringency_{t-7}}$ * Social Philanthropic Health"
  ),
  title = "Disaggregated Social Capital Regression Results",
  dep.var.labels = "Daily New Cases per Million",
  header = FALSE,
  no.space = TRUE
)
```

